### ISSUE TITLE
Add back "Powered by Esri" attribution

### ISSUE THREAD

**Issue by gavinr-maps** [Esri/esri-leaflet-static-basemap-tile#2]
### Describe the bug

Starting at Esri Leaflet v3.0.10, calling `Util.setEsriAttribution(this._map)` does not add the "Powered by Esri" attribution anymore.

https://github.com/Esri/esri-leaflet-static-basemap-tile/blob/59729d46c3fbafa1a56a1552ecaa7643b245c4f5/src/StaticBasemapTileLayer.js#L81C5-L81C40

So in this library we need to now add the "Powered by Esri" wording ourselves.

### Reproduction

1. Esri Leaflet v3.0.10: https://jsbin.com/jiwiwem/edit?html,output
    - Expected: Attribution shows "Powered by Esri"
    - Actual: Attribution shows "Powered by Esri"

2. Esri Leaflet v3.0.13 (latest): https://jsbin.com/coruyum/1/edit?html,output
    - Expected: Attribution shows "Powered by Esri"
    - Actual: Attribution **does not** show "Powered by Esri"

### System Info

```shell
Leaflet: 1.9.4
Esri Leaflet: 3.0.13
Esri Leaflet Vector: 4.2.5
```

### Additional Information

Originally reported  by @sherylgiovanni: https://github.com/Esri/esri-leaflet/issues/1396

To fix this, we can probably make a similar change to this: https://github.com/Esri/esri-leaflet-vector/pull/229

**Comment by gowin20** [comment]
Fixed in https://github.com/Esri/esri-leaflet-static-basemap-tile/releases/tag/v1.0.0-beta.2
